name: Deploy with Helm on KinD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up KinD (Kubernetes in Docker)
        uses: helm/kind-action@v1.5.0
        with:
          version: v0.20.0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Deploy with Helm
        run: helm upgrade --install user-apps ./helm-chart
