name: CI/CD Build and Deploy Kafka App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build producer jar
        run: |
          cd user-producer
          mvn clean package -DskipTests

      - name: Build consumer jar
        run: |
          cd user-consumer
          mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Producer image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-producer:latest ./user-producer
          docker push ${{ secrets.DOCKER_USERNAME }}/user-producer:latest

      - name: Build and push Consumer image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-consumer:latest ./user-consumer
          docker push ${{ secrets.DOCKER_USERNAME }}/user-consumer:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Decode and configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config

      - name: Deploy Helm chart to Kubernetes
        run: |
          helm upgrade --install user-apps ./helm-chart

      - name: Verify deployed services
        run: |
          kubectl get all
